openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server

paths:
  /event/registerForEvent:
    post:
      summary: Register for an event
      description: Route to register for an event
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eventId:
                  type: string
      responses:
        '200':
          description: Successfully registered for the event
        '401':
          description: Unauthorized

  /event/create:
    post:
      summary: Create a new event
      description: Route to create a new event
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                  format: date-time
                location:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Event created successfully
        '401':
          description: Unauthorized

  /event/getAll:
    post:
      summary: Get all events
      description: Route to get all events
      tags: [Event]
      responses:
        '200':
          description: A list of events
        '401':
          description: Unauthorized

  /event/getById:
    post:
      summary: Get event by ID
      description: Route to get an event by ID
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: Successfully retrieved the event
        '401':
          description: Unauthorized

  /event/update:
    post:
      summary: Update an event
      description: Route to update an existing event
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                  format: date-time
                location:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Event updated successfully
        '401':
          description: Unauthorized

  /event/delete:
    post:
      summary: Delete an event
      description: Route to delete an event
      tags: [Event]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: Event deleted successfully
        '401':
          description: Unauthorized
